//! Wire protocol: message format, payload types, envelopes.
//!
//! Serialization: postcard (compact, `no_std`, deterministic).
//! See SPEC.md §6 for the full protocol specification.

use serde::{Deserialize, Serialize};

// ─── Top-level transport message ──────────────────────────────────────────────

#[derive(Debug, Serialize, Deserialize)]
pub enum Message {
    Handshake(HandshakeInit),
    HandshakeAck(HandshakeAck),
    Encrypted(EncryptedEnvelope),
    FileOffer(FileOffer),
    FileChunk(FileChunk),
    FileAck(FileAck),
    Ping,
    Pong,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EncryptedEnvelope {
    /// ChaCha20-Poly1305 nonce (12 bytes)
    pub nonce: [u8; 12],
    /// Ratchet message counter (for ordering & dedup)
    pub counter: u64,
    /// Encrypted payload — max 64 KB (see SPEC.md §6.22)
    pub ciphertext: Vec<u8>,
}

// ─── Plain payload (inside EncryptedEnvelope after decryption) ───────────────

#[derive(Debug, Serialize, Deserialize)]
pub enum PlainPayload {
    // Content
    Text(String),
    /// Third-person action (/me does something)
    Action(String),
    /// Inline media: image, audio, video (SPEC.md §6.11)
    Media(MediaPayload),
    /// Link with preview (SPEC.md §6.12)
    LinkPreview(LinkPreviewPayload),

    // Message operations
    Reaction {
        message_id: [u8; 16],
        emoji: String,
    },
    Edit {
        message_id: [u8; 16],
        new_text: String,
    },
    Delete {
        message_id: [u8; 16],
    },

    // Status
    Receipt(ReceiptPayload),
    Typing(bool),

    // Files
    FileStart {
        id: [u8; 16],
        name: String,
        size: u64,
        hash: [u8; 32],
    },

    // Session management
    /// Full session reset — re-initiates PQXDH handshake (SPEC.md §4.9)
    SessionReset {
        reason: SessionResetReason,
        new_kem_pk: Vec<u8>,
    },

    // Extensibility (SPEC.md §6.16)
    /// Unknown type — old clients show "please update Aira"
    Unknown {
        type_id: u16,
        data: Vec<u8>,
    },
}

/// Wrapper with message metadata.
#[derive(Debug, Serialize, Deserialize)]
pub struct MessageMeta {
    pub payload: PlainPayload,
    /// TTL for disappearing messages (None = forever, SPEC.md §6.7)
    pub ttl: Option<std::time::Duration>,
    /// Unique message ID (16 random bytes, used for dedup & reactions)
    pub id: [u8; 16],
    /// ID of the message being replied to (SPEC.md §6.8)
    pub reply_to: Option<[u8; 16]>,
}

// ─── Payload sub-types ────────────────────────────────────────────────────────

#[derive(Debug, Serialize, Deserialize)]
pub struct MediaPayload {
    pub media_type: MediaType,
    /// BLAKE3 hash of the full file (for iroh-blobs retrieval)
    pub hash: [u8; 32],
    pub size: u64,
    /// Inline JPEG thumbnail (≤ 10 KB) for instant preview
    pub thumbnail: Option<Vec<u8>>,
    /// Duration in seconds (audio/video)
    pub duration_secs: Option<f32>,
    pub width: Option<u32>,
    pub height: Option<u32>,
}

#[derive(Debug, Serialize, Deserialize)]
pub enum MediaType {
    Image,
    Audio,
    Video,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct LinkPreviewPayload {
    pub url: String,
    pub title: Option<String>,
    pub description: Option<String>,
    /// JPEG thumbnail (≤ 10 KB) — generated by sender, not receiver
    pub thumbnail: Option<Vec<u8>>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct ReceiptPayload {
    pub message_id: [u8; 16],
    pub status: ReceiptStatus,
}

#[derive(Debug, Serialize, Deserialize)]
pub enum ReceiptStatus {
    Delivered,
    Read,
    Played,
}

#[derive(Debug, Serialize, Deserialize)]
pub enum SessionResetReason {
    StateLost,
    UserRequested,
    OutOfSync { last_valid_counter: u64 },
}

// ─── Handshake ────────────────────────────────────────────────────────────────

#[derive(Debug, Serialize, Deserialize)]
pub struct HandshakeInit {
    pub identity_pk: Vec<u8>,   // ML-DSA-65 verifying key
    pub kem_encaps_pk: Vec<u8>, // ML-KEM-768 encapsulation key
    pub x25519_pk: [u8; 32],
    pub capabilities: Capabilities,
    pub signature: Vec<u8>, // ML-DSA sign of all fields above
}

#[derive(Debug, Serialize, Deserialize)]
pub struct HandshakeAck {
    pub identity_pk: Vec<u8>,
    pub kem_ciphertext: Vec<u8>, // ML-KEM encapsulated shared secret
    pub x25519_pk: [u8; 32],
    pub capabilities: Capabilities,
    pub signature: Vec<u8>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Capabilities {
    pub min_version: u16,
    pub max_version: u16,
    pub features: u64,
}

// ─── File transfer ────────────────────────────────────────────────────────────

#[derive(Debug, Serialize, Deserialize)]
pub struct FileOffer {
    pub id: [u8; 16],
    pub name: String,
    pub size: u64,
    pub hash: [u8; 32], // BLAKE3
}

#[derive(Debug, Serialize, Deserialize)]
pub struct FileChunk {
    pub file_id: [u8; 16],
    pub offset: u64,
    pub data: Vec<u8>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct FileAck {
    pub file_id: [u8; 16],
    pub bytes_received: u64,
}

// ─── Errors ───────────────────────────────────────────────────────────────────

#[derive(Debug, thiserror::Error)]
pub enum AiraError {
    #[error("seed derivation failed: {0}")]
    SeedDerivation(String),
    #[error("invalid seed phrase")]
    InvalidSeedPhrase,
    #[error("encryption failed")]
    Encryption,
    #[error("decryption failed (wrong key or corrupted data)")]
    Decryption,
    #[error("handshake failed: {0}")]
    Handshake(String),
    #[error("protocol version mismatch")]
    VersionMismatch,
    #[error("message too large: {size} bytes (max 65536)")]
    MessageTooLarge { size: usize },
    #[error("storage error: {0}")]
    Storage(String),
    #[error("serialization error: {0}")]
    Serialization(String),
}
